### ISSUE TITLE
argument must be 9-item sequence, not None

### ISSUE THREAD

**Issue by yasabaz** [ahernp/django-feedreader#13]
I  add  rss feed of this  site:http://en.farsnews.com/rss.aspx and i get this error
```
TypeError at /admin/feedreader/feed/add/

argument must be 9-item sequence, not None

Request Method: 	POST
Request URL: 	http://127.0.0.1:8000/admin/feedreader/feed/add/
Django Version: 	1.9.1
Exception Type: 	TypeError
Exception Value: 	

argument must be 9-item sequence, not None

Exception Location: 	/home/qwer/Projects/feedreader/local/lib/python2.7/site-packages/feedreader/utils.py in poll_feed, line 178
Python Executable: 	/home/qwer/Projects/feedreader/bin/python
Python Version: 	2.7.13
Python Path: 	
 ```

**Comment by ahernp** [comment]
I believe that the problem is that the `pubDate` values on that feed have no timezone information.

My `django-feedreader` app uses a library called `feedparser` to parse the feed content. That library supports a wide range of date-time formats (detailed [here](https://github.com/kurtmckee/feedparser/blob/develop/docs/date-parsing.rst#recognized-date-formats)).

The `pubDate` values on that feed (e.g. `Thu, 4 May 2017 19:40:17`) are not recognised.

I will change `django-feedreader` to default to using a published time of "now" when no `pubDate` is returned. I'll let you know when that change has been done.

**Comment by ahernp** [comment]
@yasabaz I've updated the code al allow for invalid `pubDate` values. See e344ec9126240ef251e43452be7845f8804329a7

With these changes I was able to process the feed you mentioned.

**Comment by yasabaz** [comment]
thank @ahernp  so much
