### ISSUE TITLE
ImportError: cannot import name build_context

### ISSUE THREAD

**Issue by Mr-Virtuoso** [ahernp/django-feedreader#15]
Hi, I try using this project but in project folder we have utils folder and utils.py both, and when i try using feedreader error raise that 
```
lib/python2.7/site-packages/feedreader/views.py", line 18, in <module>
from .utils import build_context
ImportError: cannot import name build_context
```
i check and get that views.py try to use utils folder but we need utils.py 
how can we fix this ?

**Comment by ahernp** [comment]
I could only recreate the problem by adding a `utils` directory to `lib/python2.7/site-packages/feedreader` but you are not supposed to edit the contents of third party-packages like that.

If you want to amend `django-feedreader` then clone the source code from [GitHub](https://github.com/ahernp/django-feedreader) and amend that instead. 

However, Python doesn't support having a package and module of the same name in the same directory since it cannot figure out which one to import. You would have to call your directory something else or delete the `utils.py` module (having added its code to the new package, perhaps in `utils/__init__.py).

I hope that this helps explain what is going on.

**Comment by Mr-Virtuoso** [comment]
yeap , i use this project on my django project and installed it with pip, but i guess utils forlder created to my project only , i supposed it's create by you in feedreader so i think that i should tell you about this. thanks for answering

**Comment by ahernp** [comment]
No problem.
