### ISSUE TITLE
cannot import name build_context

### ISSUE THREAD

**Issue by ahmetalsan** [ahernp/django-feedreader#9]
Do you know what is the solution?

cannot import name build_context
Request Method: GET
Request URL:    http://project.dev/admin/
Django Version: 1.8
Exception Type: ImportError
Exception Value:  
cannot import name build_context
Exception Location: /home/vagrant/venv/local/lib/python2.7/site-packages/feedreader/views.py in <module>, line 18
Python Executable:  /home/vagrant/venv/bin/python
Python Version: 2.7.3
Python Path:  
['/vagrant/merkezhaber',
 '/home/vagrant/venv/bin',
 '/home/vagrant/venv/lib/python2.7',
 '/home/vagrant/venv/lib/python2.7/plat-linux2',
 '/home/vagrant/venv/lib/python2.7/lib-tk',
 '/home/vagrant/venv/lib/python2.7/lib-old',
 '/home/vagrant/venv/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-linux2',
 '/usr/lib/python2.7/lib-tk',
 '/home/vagrant/venv/local/lib/python2.7/site-packages']
Server time:    Tue, 21 Jul 2015 21:44:40 +0000

**Comment by ahmetalsan** [comment]
from .utils import * fixed for me

**Comment by ahernp** [comment]
Sorry, I am unable to recreate this problem and cannot explain what went wrong for you. That import works for me with the same version of Django and Python.

The previous statement in the `views.py` module does similar imports (i.e. `feedreader/views.py`, line 17) which must have worked for you; The views call `build_context` which is the name of the function it tries to import so using `import *` should not make a difference.

Can you recreate the problem? What happens when you run the unit tests (`python manage.py test`)?
